# Generated by Django 5.1.4 on 2024-12-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration_api', '0002_user_display_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='deviation',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='input_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measurement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='output_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='threshold',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='tolerance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='uncertainty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='unit1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
